=begin
#Keycloak Admin REST API

#This is a REST API reference for the Keycloak Admin

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KeycloakAdminClient::AccessTokenCertConf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KeycloakAdminClient::AccessTokenCertConf do
  let(:instance) { KeycloakAdminClient::AccessTokenCertConf.new }

  describe 'test an instance of AccessTokenCertConf' do
    it 'should create an instance of AccessTokenCertConf' do
      expect(instance).to be_instance_of(KeycloakAdminClient::AccessTokenCertConf)
    end
  end
  describe 'test attribute "x5t_s256"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
