=begin
#Keycloak Admin REST API

#This is a REST API reference for the Keycloak Admin

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KeycloakAdminClient::AuthenticatorConfigRepresentation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KeycloakAdminClient::AuthenticatorConfigRepresentation do
  let(:instance) { KeycloakAdminClient::AuthenticatorConfigRepresentation.new }

  describe 'test an instance of AuthenticatorConfigRepresentation' do
    it 'should create an instance of AuthenticatorConfigRepresentation' do
      expect(instance).to be_instance_of(KeycloakAdminClient::AuthenticatorConfigRepresentation)
    end
  end
  describe 'test attribute "_alias"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "config"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
