=begin
#Keycloak Admin REST API

#This is a REST API reference for the Keycloak Admin

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KeycloakAdminClient::Permission
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KeycloakAdminClient::Permission do
  let(:instance) { KeycloakAdminClient::Permission.new }

  describe 'test an instance of Permission' do
    it 'should create an instance of Permission' do
      expect(instance).to be_instance_of(KeycloakAdminClient::Permission)
    end
  end
  describe 'test attribute "claims"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "rsid"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "rsname"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "scopes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
