=begin
#Keycloak Admin REST API

#This is a REST API reference for the Keycloak Admin

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KeycloakAdminClient::ProfileInfoRepresentation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KeycloakAdminClient::ProfileInfoRepresentation do
  let(:instance) { KeycloakAdminClient::ProfileInfoRepresentation.new }

  describe 'test an instance of ProfileInfoRepresentation' do
    it 'should create an instance of ProfileInfoRepresentation' do
      expect(instance).to be_instance_of(KeycloakAdminClient::ProfileInfoRepresentation)
    end
  end
  describe 'test attribute "disabled_features"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "experimental_features"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "preview_features"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
