=begin
#Keycloak Admin REST API

#This is a REST API reference for the Keycloak Admin

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1-SNAPSHOT

=end

# Common files
require 'keycloak_admin_client/api_client'
require 'keycloak_admin_client/api_error'
require 'keycloak_admin_client/version'
require 'keycloak_admin_client/configuration'

# Models
require 'keycloak_admin_client/models/access_token'
require 'keycloak_admin_client/models/access_token_access'
require 'keycloak_admin_client/models/access_token_authorization'
require 'keycloak_admin_client/models/access_token_cert_conf'
require 'keycloak_admin_client/models/address_claim_set'
require 'keycloak_admin_client/models/authentication_execution_export_representation'
require 'keycloak_admin_client/models/authentication_execution_info_representation'
require 'keycloak_admin_client/models/authentication_execution_representation'
require 'keycloak_admin_client/models/authentication_flow_representation'
require 'keycloak_admin_client/models/authenticator_config_info_representation'
require 'keycloak_admin_client/models/authenticator_config_representation'
require 'keycloak_admin_client/models/certificate_representation'
require 'keycloak_admin_client/models/client_initial_access_create_presentation'
require 'keycloak_admin_client/models/client_initial_access_presentation'
require 'keycloak_admin_client/models/client_mappings_representation'
require 'keycloak_admin_client/models/client_policies_representation'
require 'keycloak_admin_client/models/client_policy_condition_representation'
require 'keycloak_admin_client/models/client_policy_executor_representation'
require 'keycloak_admin_client/models/client_policy_representation'
require 'keycloak_admin_client/models/client_profile_representation'
require 'keycloak_admin_client/models/client_profiles_representation'
require 'keycloak_admin_client/models/client_representation'
require 'keycloak_admin_client/models/client_scope_evaluate_resource_protocol_mapper_evaluation_representation'
require 'keycloak_admin_client/models/client_scope_representation'
require 'keycloak_admin_client/models/component_export_representation'
require 'keycloak_admin_client/models/component_representation'
require 'keycloak_admin_client/models/config_property_representation'
require 'keycloak_admin_client/models/credential_representation'
require 'keycloak_admin_client/models/federated_identity_representation'
require 'keycloak_admin_client/models/global_request_result'
require 'keycloak_admin_client/models/group_representation'
require 'keycloak_admin_client/models/id_token'
require 'keycloak_admin_client/models/identity_provider_mapper_representation'
require 'keycloak_admin_client/models/identity_provider_representation'
require 'keycloak_admin_client/models/json_node'
require 'keycloak_admin_client/models/key_store_config'
require 'keycloak_admin_client/models/keys_metadata_representation'
require 'keycloak_admin_client/models/keys_metadata_representation_key_metadata_representation'
require 'keycloak_admin_client/models/management_permission_reference'
require 'keycloak_admin_client/models/mappings_representation'
require 'keycloak_admin_client/models/memory_info_representation'
require 'keycloak_admin_client/models/multivalued_hash_map'
require 'keycloak_admin_client/models/partial_import_representation'
require 'keycloak_admin_client/models/password_policy_type_representation'
require 'keycloak_admin_client/models/permission'
require 'keycloak_admin_client/models/policy_representation'
require 'keycloak_admin_client/models/profile_info_representation'
require 'keycloak_admin_client/models/protocol_mapper_representation'
require 'keycloak_admin_client/models/provider_representation'
require 'keycloak_admin_client/models/realm_events_config_representation'
require 'keycloak_admin_client/models/realm_representation'
require 'keycloak_admin_client/models/required_action_provider_representation'
require 'keycloak_admin_client/models/resource_representation'
require 'keycloak_admin_client/models/resource_server_representation'
require 'keycloak_admin_client/models/role_representation'
require 'keycloak_admin_client/models/role_representation_composites'
require 'keycloak_admin_client/models/roles_representation'
require 'keycloak_admin_client/models/scope_mapping_representation'
require 'keycloak_admin_client/models/scope_representation'
require 'keycloak_admin_client/models/server_info_representation'
require 'keycloak_admin_client/models/spi_info_representation'
require 'keycloak_admin_client/models/synchronization_result'
require 'keycloak_admin_client/models/system_info_representation'
require 'keycloak_admin_client/models/test_ldap_connection_representation'
require 'keycloak_admin_client/models/user_consent_representation'
require 'keycloak_admin_client/models/user_federation_mapper_representation'
require 'keycloak_admin_client/models/user_federation_provider_representation'
require 'keycloak_admin_client/models/user_representation'

# APIs
require 'keycloak_admin_client/api/attack_detection_api'
require 'keycloak_admin_client/api/authentication_management_api'
require 'keycloak_admin_client/api/client_attribute_certificate_api'
require 'keycloak_admin_client/api/client_initial_access_api'
require 'keycloak_admin_client/api/client_registration_policy_api'
require 'keycloak_admin_client/api/client_role_mappings_api'
require 'keycloak_admin_client/api/client_scopes_api'
require 'keycloak_admin_client/api/clients_api'
require 'keycloak_admin_client/api/component_api'
require 'keycloak_admin_client/api/groups_api'
require 'keycloak_admin_client/api/identity_providers_api'
require 'keycloak_admin_client/api/key_api'
require 'keycloak_admin_client/api/protocol_mappers_api'
require 'keycloak_admin_client/api/realms_admin_api'
require 'keycloak_admin_client/api/role_mapper_api'
require 'keycloak_admin_client/api/roles_api'
require 'keycloak_admin_client/api/roles_by_id_api'
require 'keycloak_admin_client/api/root_api'
require 'keycloak_admin_client/api/scope_mappings_api'
require 'keycloak_admin_client/api/user_storage_provider_api'
require 'keycloak_admin_client/api/users_api'

module KeycloakAdminClient
  class << self
    # Customize default settings for the SDK using block.
    #   KeycloakAdminClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
